DROP TABLE IF EXISTS Supplier CASCADE;

DROP TABLE IF EXISTS Client CASCADE;

DROP TABLE IF EXISTS Manager CASCADE;

DROP TABLE IF EXISTS SparePart CASCADE;

DROP TABLE IF EXISTS Automobile CASCADE;

DROP TABLE IF EXISTS FinancialTransaction CASCADE;

DROP TABLE IF EXISTS ServiceMaintenance CASCADE;

DROP TABLE IF EXISTS Sale CASCADE;

DROP TABLE IF EXISTS SaleAutomobile CASCADE;

DROP TABLE IF EXISTS SaleSparePart CASCADE;

DROP TABLE IF EXISTS Complaint CASCADE;

DROP TABLE IF EXISTS TestDrive CASCADE;